server:
  port: 8083

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/microservices
      database: microservices

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    hostname: localhost
    prefer-ip-address: true
